client_acceptance:
  client_information_integrity_check:
    description: >
      Gather and verify preliminary client information for {company_name} ({company_ticker}),
      identified by central index key {central_index_key}. Ensure that all information used 
      in the evaluation is from {year} or earlier. Perform conflict of interest checks 
      to verify compliance with independence standards. Identify any initial risk factors 
      or ethical concerns that may affect the engagement decision. Search and extract relevant 
      information from multiple independent sources, cross-referencing details for consistency 
      and corroboration. Utilize PCAOB guidelines as outlined in the json provided to assess the integrity and reputation of the 
      prospective client’s management and owners.
    expected_output: >
      A detailed profile for {company_name}, including industry classification, financial 
      reporting details, and conflict of interest assessment. A summary of identified 
      ethical concerns, risk factors, or independence issues, ensuring that all findings 
      adhere to the {year} restriction.

  client_integrity_background_check:
    description: >
      Assess the integrity, reputation, and legal history of {company_name} ({company_ticker}). 
      Perform due diligence by searching public records, court filings, and media sources for 
      any evidence of fraud, unethical behavior, or past regulatory violations. Conduct a sentiment 
      analysis of financial news, social media, and whistleblower reports to detect negative 
      patterns. Cross-reference findings for consistency and corroboration with SEC, PCAOB, and 
      industry watchdog reports.
    expected_output: >
      A reputation and legal risk profile summarizing key integrity concerns, prior regulatory 
      penalties, litigation risks, and any indicators of unethical business practices. If the 
      company has been involved in legal disputes or financial misconduct, provide a risk rating 
      with supporting evidence.

  financial_risk_independence_assessment:
    description: >
      Analyze the financial stability and risk profile of {company_name} ({company_ticker}), 
      ensuring that only financial statements and risk assessments from {year} or earlier 
      are considered. Assess creditworthiness, potential audit risks, and compliance 
      with PCAOB financial integrity standards as outlined in the json provided. Verify auditor independence by confirming 
      that no conflicts of interest, financial ties, or consulting relationships exist 
      that could impair objectivity. Search and extract relevant information from multiple 
      independent sources, cross-referencing details for consistency and corroboration.
      Follow PCAOB guidelines to ensure that financial risk factors, auditor independence 
      checks, and material misstatement risks are appropriately evaluated and documented.
    expected_output: >
      A comprehensive financial risk assessment report for {company_name}, including an 
      analysis of financial health, creditworthiness, and potential audit risks based on 
      data up to {year}. A clear determination of whether auditor independence is maintained, 
      with documented findings and recommendations on risk mitigation or engagement termination.

  auditor_independence_verification:
    description: >
      Ensure the independence of {audit_firm} in relation to {company_name} ({company_ticker}). 
      Identify any financial relationships, prior engagements, or advisory roles that could 
      impair objectivity. Verify compliance with PCAOB and SEC independence rules, checking 
      historical auditor-client relationships and consulting agreements. Ensure that neither 
      {audit_firm} nor its key personnel have direct or indirect financial ties to the client. 
      Use publicly available filings and past audit disclosures for validation.
    expected_output: >
      A report detailing auditor independence verification, identifying any threats to independence, 
      prior engagements, financial relationships, or consulting ties. If any independence issues 
      exist, provide recommendations for mitigating risks or rejecting the engagement.

  competence_predecessor_auditor_review:
    description: >
      Evaluate whether {audit_firm} has the necessary expertise and resources to effectively 
      conduct the audit for {company_name} ({company_ticker}). Ensure that all assessments 
      of competence and past audit engagements consider only information available in {year} 
      or earlier. If applicable, analyze predecessor audit reports and identify potential risk 
      factors, disputes, or limitations from past engagements. Search and extract relevant 
      information from multiple independent sources, cross-referencing details for consistency 
      and corroboration. Utilize PCAOB compliance guidelines as outlined in the json provided to assess the 
      firm’s ability to perform the audit effectively, ensuring technical competence, sufficient 
      staffing, and independence from past audit influences.
    expected_output: >
      A competency evaluation report detailing {audit_firm}'s capacity to handle the 
      engagement for {company_name}. A summary of findings from past audits (if applicable), 
      ensuring that all references adhere to the {year} constraint. Recommendations on whether 
      additional expertise is needed or if the engagement should proceed.

  engagement_scope_regulatory_compliance:
    description: >
      Define the expected scope of the audit for {company_name} ({company_ticker}), ensuring 
      that only transactions, regulatory requirements, and risk factors from {year} or earlier 
      are evaluated. Identify key areas of financial reporting that require attention, such as 
      complex transactions, multiple subsidiaries, or industry-specific regulations. Ensure 
      alignment with PCAOB regulatory requirements and cross-check applicable compliance standards 
      as outlined in the json provided. 
    expected_output: >
      A detailed engagement scope document specifying audit objectives, high-risk areas, 
      regulatory compliance considerations, and engagement limitations. Ensure that the 
      audit scope aligns with industry best practices and risk tolerance levels.

  final_risk_aggregation_decision_modeling:
    description: >
      Aggregate all findings from previous steps to generate a final risk assessment for 
      {company_name} ({company_ticker}). Assign a weighted risk score based on financial 
      stability, integrity concerns, auditor independence, litigation history, and regulatory 
      compliance. Model different risk scenarios and recommend either acceptance, conditional 
      acceptance (with safeguards), or rejection of the engagement. Ensure that decision-making 
      follows PCAOB regulatory guidelines and best practices.
    expected_output: >
      A **comprehensive final client acceptance risk report**, consolidating findings from:  
      **Preliminary Information Gathering & Conflict Check**,  
      **Client Integrity & Background Check**,  
      **Financial Health & Risk Assessment**,  
      **Auditor Independence Check**,  
      **Firm Competence & Resource Assessment**,  
      **Predecessor Auditor Review**,  
      **Engagement Scope & Risk Evaluation**,  
      with a **Documented Decision** on whether to accept or decline the client.  

      The report should be detailed, with comprehensive four paragraphs per section, structured, and well-documented. Output in **Markdown format**.  

  engagement_letter_documentation:
    description: >
      Generate an engagement letter formalizing the audit agreement between {audit_firm} and 
      {company_name} ({company_ticker}). Ensure that the document outlines the scope, auditor responsibilities, 
      client obligations, and compliance requirements. Structure the engagement letter in 
      accordance with PCAOB and SEC standards. Additionally, document all due diligence steps 
      performed throughout the client acceptance process to ensure audit transparency.
    expected_output: >
      A **formal engagement letter**, structured as a Markdown document for final approval.  
      - **File:** `engagement_letter.md`
      - Includes audit scope, legal disclaimers, and responsibilities.
      - Ensures compliance with **PCAOB and SEC** regulations.
