evidence_evaluation_task:
  description: >
    Conduct a thorough evaluation of the audit evidence collected for {company_name} ({company_ticker}). 
    Assess the sufficiency, reliability, and relevance of the evidence gathered during the fieldwork phase. 
    Analyze the evidence in relation to the audit objectives and risk areas identified in the planning phase. 
    Ensure all evaluations are based on information from {year} or earlier.
  expected_output: >
    A comprehensive report detailing the evaluation of audit evidence, including assessment of evidence 
    sufficiency and appropriateness, analysis of reliability and relevance, identification of gaps or 
    inconsistencies, and recommendations for additional evidence collection if necessary. The report 
    should be formatted in Markdown without '```'.
  agent: researcher

misstatement_analysis_task:
  description: >
    Review and analyze identified misstatements in the financial statements of {company_name} ({company_ticker}).
    Classify misstatements as factual, judgmental, or projected. Assess the materiality of individual and 
    aggregate misstatements. Evaluate the impact of uncorrected misstatements on the financial statements.
    Consider only information from {year} or earlier in your analysis.
  expected_output: >
    A detailed report on misstatement analysis, including classification of identified misstatements, 
    assessment of materiality for individual and aggregate misstatements, evaluation of the impact of 
    uncorrected misstatements, and recommendations for adjustments or disclosures. The report should 
    be formatted in Markdown without '```'.
  agent: researcher

conclusion_formation_task:
  description: >
    Based on the evidence evaluation and misstatement analysis, form conclusions on the financial 
    statement assertions for {company_name} ({company_ticker}). Assess the overall fairness of the 
    financial statements. Determine if there are any significant deficiencies or material weaknesses 
    in internal controls. Consider only information from {year} or earlier in your conclusions.
  expected_output: >
    A comprehensive report detailing audit conclusions, including conclusions on financial statement 
    assertions, assessment of overall fairness of financial statements, identification of significant 
    deficiencies or material weaknesses in internal controls, and the basis for the audit opinion. 
    The report should be formatted in Markdown without '```'.
  agent: reporting_analyst

audit_report_drafting_task:
  description: >
    Draft the audit report for {company_name} ({company_ticker}) based on the conclusions formed. 
    Include an executive summary, detailed findings, recommendations, and the basis for the audit opinion. 
    Ensure the report adheres to professional standards and regulatory requirements. Use only information 
    from {year} or earlier in the report.
  expected_output: >
    A complete draft audit report, including an executive summary, detailed audit findings and their 
    implications, recommendations for improvements, basis for the audit opinion, and any required 
    disclosures or emphasis of matter paragraphs. The report should be formatted in Markdown without '```'.
  agent: reporting_analyst

