preliminary_engagement_review:
  description: >
    Today's date is {current_date}.

    Conduct an initial assessment of the audit engagement for {company_name} ({company_ticker}), identified by central index key {central_index_key}
    based on the following Phase 1 report:

    ```{engagement_scope_and_strategy}```

    Ensure alignment with regulatory requirements and industry best practices. Verify prior audit 
    engagement files for unresolved issues, disagreements, or material misstatements from previous 
    years. Identify major business changes, new regulatory considerations, and internal control updates 
    since the last audit. 

    Establish materiality thresholds for the audit, calculating overall materiality using industry benchmarks, 
    such as revenue percentage, net income, or total assets. Determine performance materiality 
    based on prior misstatements and business risk.

    Ensure that all information used in the evaluation is from {year} or earlier. Search and extract relevant 
    information from multiple independent sources, cross-referencing details for consistency 
    and corroboration. Utilize PCAOB guidelines as outlined in the json provided to ensure compliance. 
    Output the findings to the markdown file in a detailed and comprehensive manner.
    If not enough information is found, clearly state **Additional Data Needed**. Do not fabricate information.
  expected_output: >
    A detailed **Preliminary Audit Engagement Report** for {company_name}, detailing prior audit findings, 
    unresolved issues, key business changes, materiality thresholds, and preliminary risk factors in a markdown file. 
    Ensure all information is sourced from {year} or earlier and complies with regulatory audit planning requirements with appropriate source citations.
    The document should be detailed, with comprehensive paragraphs per section and citations, well-structured, 
    and formatted in **Markdown for seamless integration** into the audit workflow.

business_risk_and_fraud_assessment:
  description: >
    Today's date is {current_date}.

    Develop a comprehensive understanding of {company_name} ({company_ticker})'s business operations, 
    industry landscape, and risk factors that may impact financial statements, building on the following Phase 1 reports:

    ```{client_background_and_integrity_assessment}```

    ```{financial_risk_and_independence_assessment}```

    Identify significant financial reporting, operational, and fraud risks. 

    Conduct a forensic analysis of historical financial data to detect unusual trends, outliers, or inconsistencies. 
    Identify potential fraud schemes and financial misrepresentation risks. Map risks to key financial 
    statement areas and disclosures to determine focus areas for substantive testing.

    Ensure that all information used in the evaluation is from {year} or earlier. Search and extract relevant 
    information from multiple independent sources, cross-referencing details for consistency 
    and corroboration. Utilize PCAOB guidelines as outlined in the json provided to ensure compliance. 
    Output the findings to the markdown file in a detailed and comprehensive manner.
    If not enough information is found, clearly state **Additional Data Needed**. Do not fabricate information.
  expected_output: >
    A detailed **Business & Fraud Risk Assessment Report** detailing {company_name}'s industry environment, 
    financial reporting risks, fraud vulnerabilities, and key risk indicators in a markdown file. The report should categorize 
    risks by severity and likelihood, highlighting high-risk financial statement areas and preliminary 
    fraud risk assessment with appropriate source citations.
    The document should be detailed, with comprehensive paragraphs per section and citations, well-structured, 
    and formatted in **Markdown for seamless integration** into the audit workflow.

internal_control_system_evaluation:
  description: >
    Today's date is {current_date}.

    Assess the design and effectiveness of {company_name} ({company_ticker})’s internal control system 
    relevant to financial reporting. Evaluate the entity’s control environment, risk assessment process, 
    control activities, information systems, and monitoring mechanisms. Identify key control deficiencies, 
    material weaknesses, and areas requiring additional substantive testing.
    
    Perform preliminary analytical procedures on financial statements to identify unusual trends, anomalies, 
    or risk indicators. Compare financial data across multiple periods to detect unexpected variances.
    
    Ensure that all information used in the evaluation is from {year} or earlier. Search and extract relevant 
    information from multiple independent sources, cross-referencing details for consistency 
    and corroboration. Utilize PCAOB guidelines as outlined in the json provided to ensure compliance. 
    Output the findings to the markdown file in a detailed and comprehensive manner.
    If not enough information is found, clearly state **Additional Data Needed**. Do not fabricate information.
  expected_output: >
    A detailed **Internal Controls Assessment Report**, detailing key control risks, strengths, and weaknesses in markdown file. 
    A classification of control deficiencies as either material weaknesses or significant deficiencies, 
    with recommendations on control reliance and additional testing with appropriate source citations.
    The document should be detailed, with comprehensive paragraphs per section and citations, well-structured, 
    and formatted in **Markdown for seamless integration** into the audit workflow.

audit_strategy_and_team_allocation:
  description: >
    Today's date is {current_date}.

    Develop an overall audit strategy for {company_name} ({company_ticker}), aligning audit procedures 
    with identified risk factors. Assign risk levels to financial statement line items and disclosures, 
    determining the nature, timing, and extent of planned audit procedures. 
    
    Ensure that all information used in the evaluation is from {year} or earlier. Search and extract relevant 
    information from multiple independent sources, cross-referencing details for consistency 
    and corroboration. Utilize PCAOB guidelines as outlined in the json provided to ensure compliance. 
    Output the findings to the markdown file in a detailed and comprehensive manner.
    If not enough information is found, clearly state **Additional Data Needed**. Do not fabricate information.
  expected_output: >
    A detailed **Audit Strategy Report** detailing risk-mapped audit procedures, categorized into 
    high, medium, and low-risk areas in markdown file. The document should provide a recommended approach for 
    substantive testing and control reliance with appropriate source citations.
    The document should be detailed, with comprehensive paragraphs per section and citations, well-structured, 
    and formatted in **Markdown for seamless integration** into the audit workflow.