control_testing_task:
  description: >
    Conduct tests of controls for {company_name} ({company_ticker}) to evaluate their operating effectiveness in preventing, detecting, 
    and correcting material misstatements. Perform procedures such as conducting interviews with client personnel, observing business processes, 
    inspecting documents, and reconstructing processes to compare with the numbers provided by the client. Generate questions based on information 
    gathered from previous phases and attempt to answer these questions using publicly available information (e.g., reviews, blog posts). 
    Ensure that all information used in the evaluation is from {year} or earlier. Search and extract relevant information from multiple independent sources, 
    cross-referencing details for consistency and corroboration. Utilize PCAOB guidelines as outlined in the JSON provided to ensure compliance. 
    Output the findings to the markdown file in a detailed and comprehensive manner.
  expected_output: >
    A comprehensive report detailing control testing results, including: Evaluation of operating effectiveness of controls,
    Insights gained from interviews, observations, and document inspections, Identification of control deficiencies or weaknesses,
    Recommendations for improvements, The report should be formatted in Markdown without '```'.
  agent: control_testing_agent

process_mining_task:
  description: >
    Perform process mining for {company_name} ({company_ticker}) by examining event logs and analyzing internal documents (if available) to identify patterns 
    and gain insights into business processes. Evaluate relationships between business processes and financial accounts to detect anomalies or discrepancies. 
    Ensure that all information used is from {year} or earlier. Search multiple independent sources to corroborate findings. Utilize PCAOB guidelines as outlined 
    in JSON provided to ensure compliance. Output findings systematically in a markdown file.
  expected_output: >
    A detailed report summarizing process mining insights, including: Patterns detected in event logs or documents,
    Relationships between business processes and financial accounts, Identification of discrepancies or anomalies,
    Recommendations for further investigation, The report should be formatted in Markdown without '```'.
  agent: process_mining_agent

substantive_testing_task:
  description: >
    Conduct substantive testing procedures for {company_name} ({company_ticker}) to detect material misstatements in transactions, account balances, 
    and disclosures. Perform tests of details and substantive analytical procedures by analyzing transactions and financial documents/contracts (if available). 
    Identify anomalies or unusual trends using AI-driven anomaly detection techniques (e.g., deep learning models). Ensure that all information used is from {year} 
    or earlier. Search multiple independent sources to corroborate findings. Utilize PCAOB guidelines as outlined in JSON provided to ensure compliance. Output findings systematically in a markdown file.
  expected_output: >
    A comprehensive report detailing substantive testing results, including: Analysis of transactions, account balances, and disclosures,
    Identification of anomalies or unusual trends,  Recommendations for adjustments or further investigation,
    The report should be formatted in Markdown without '```
  agent: substantive_testing_agent

evidence_gathering_task:
  description: >
    Compile relevant audit evidence collected during testing procedures for {company_name} ({company_ticker}). Ensure that evidence is sufficient, appropriate, 
    reliable, and relevant to support audit conclusions. Summarize insights concisely while maintaining proper organization and referencing. Ensure that all 
    information used is from {year} or earlier. Search multiple independent sources to corroborate findings. Utilize PCAOB guidelines as outlined in JSON provided 
    to ensure compliance. Output findings systematically in a markdown file.
  expected_output: >
    A detailed markdown report summarizing audit evidence collected during testing procedures, including: Description of evidence collected,
    Cross-references to relevant tasks (e.g., control testing, substantive testing), Recommendations for further investigation if necessary.
  agent: evidence_gathering_agent
