name: Deploy Airflow to GCP VM

on:
  push:
    branches:
      - 10K_processor  # ✅ Deploy only when pushing to `10K_processor` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: 10K_processor

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Create GCE VM (CPU only)
        run: |
          gcloud compute instances list --filter="name=airflow-cpu-vm" | grep airflow-cpu-vm || \
          gcloud compute instances create airflow-cpu-vm \
            --machine-type n1-standard-4 \
            --image-family=common-container \
            --image-project=deeplearning-platform-release \
            --boot-disk-size=200GB \
            --maintenance-policy MIGRATE \
            --restart-on-failure \
            --scopes=cloud-platform \
            --tags http-server \
            --zone us-east1-c  # ✅ Pick a valid CPU-only zone

      - name: Copy Airflow Files to GCE VM
        run: |
          gcloud compute scp --recurse dags airflow-cpu-vm:~/Processor_10K/
          gcloud compute scp --recurse docker-compose.yml airflow-cpu-vm:~/Processor_10K/
          gcloud compute scp --recurse Dockerfile airflow-cpu-vm:~/Processor_10K/
          gcloud compute scp --recurse requirements.txt airflow-cpu-vm:~/Processor_10K/

      - name: Deploy Airflow with Docker on VM
        run: |
          gcloud compute ssh airflow-cpu-vm --command "
            sudo apt update &&
            sudo apt install -y docker.io &&
            cd ~/Processor_10K &&
            docker-compose down &&
            docker-compose build &&
            docker-compose up -d
          "
