name: 10K Processing Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 10K_processor

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      REGION: us-east1
      REPOSITORY_NAME: auditpulse-images

    defaults:
      run:
        working-directory: DataPipeline/Processor_10K

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Authenticate With GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Run Tests
        env:
          PYTHONPATH: ${{ github.workspace }}/DataPipeline/Processor_10K
        run: pytest tests/

      - name: Test Success Notification
        if: success()
        run: echo "✅ All tests passed. Proceeding to deployment."

      - name: Set up GCP CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure GCP Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Single Airflow Image
        run: |
          IMAGE_NAME="${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/airflow"
          GITHUB_SHA="${{ github.sha }}"

          echo "🚀 Building Docker image: $IMAGE_NAME"
          docker build -t "$IMAGE_NAME:$GITHUB_SHA" -t "$IMAGE_NAME:latest" .

          echo "🚀 Pushing Docker image to Artifact Registry..."
          docker push "$IMAGE_NAME:$GITHUB_SHA"
          docker push "$IMAGE_NAME:latest"

          echo "✅ Successfully pushed Airflow image!"

      - name: Deployment Success Notification
        if: success()
        run: echo "✅ Docker image successfully created and pushed to Google Artifact Registry."

      - name: Deployment Failure Notification
        if: failure()
        run: echo "❌ Deployment failed. Check logs for more details."
