name: Policy Creation Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - 10K_processor

jobs:
  policy_creation_test_and_deploy:
    runs-on: ubuntu-latest
    env:
      REGION: us-east1
      REPOSITORY_NAME: auditpulse-images

    defaults:
      run:
        working-directory: DataProcessing/Processor_10K

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Authenticate With GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Run Tests
        env:
          PYTHONPATH: ${{ github.workspace }}/DataProcessing/Processor_10K
        run: pytest tests/

      - name: Test Success Notification
        if: success()
        run: echo "✅ All tests passed. Proceeding to deployment."

      - name: Set up GCP CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure GCP Project
        run: gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for Google Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build & Push Docker Images with `docker-compose`
        if: success()
        run: |
          IMAGE_REGISTRY="${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY_NAME }}"
          
          echo "🚀 Updating docker-compose.yml to use Google Artifact Registry..."
          sed -i "s|image: .*_webserver|image: $IMAGE_REGISTRY/airflow-webserver:latest|g" docker-compose.yml
          sed -i "s|image: .*_scheduler|image: $IMAGE_REGISTRY/airflow-scheduler:latest|g" docker-compose.yml
          sed -i "s|image: .*_postgres|image: $IMAGE_REGISTRY/airflow-postgres:latest|g" docker-compose.yml
          
          docker pull postgres:13
          
          echo "🚀 Building images using docker-compose..."
          docker-compose build
          
          echo "🚀 Listing built Docker images:"
          docker images
          
          if ! docker images | grep -q "processor_10k_postgres"; then
            echo "⚠️ Postgres image missing! Tagging manually..."
            docker tag postgres "$IMAGE_REGISTRY/airflow-postgres:latest"
          fi
          
          echo "🚀 Pushing all images to Google Artifact Registry..."
          docker-compose push

      - name: Deployment Success Notification
        if: success()
        run: echo "✅ Docker Compose images successfully created and pushed to Google Artifact Registry."

      - name: Deployment Failure Notification
        if: failure()
        run: echo "❌ Deployment failed. Check logs for more details."
