name: Deploy Airflow to GCP VM with GPU

on:
  push:
    branches:
      - 10K_processor

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: 10K_processor

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

      - name: Create GCE VM with GPU
        run: |
          gcloud compute instances create airflow-gpu-vm \
            --machine-type n1-standard-4 \
            --accelerator type=nvidia-tesla-t4,count=1 \
            --image-family=common-container \
            --image-project=deeplearning-platform-release \
            --boot-disk-size=200GB \
            --maintenance-policy TERMINATE \
            --scopes=cloud-platform \
            --metadata install-nvidia-driver=True \
            --tags http-server \
            --zone us-central1-a

      - name: Copy Airflow Files to GCE VM
        run: |
          gcloud compute scp --recurse dags airflow-gpu-vm:~/Processor_10K/
          gcloud compute scp --recurse docker-compose.yml airflow-gpu-vm:~/Processor_10K/
          gcloud compute scp --recurse Dockerfile airflow-gpu-vm:~/Processor_10K/
          gcloud compute scp --recurse requirements.txt airflow-gpu-vm:~/Processor_10K/

      - name: Deploy Airflow with Docker on VM
        run: |
          gcloud compute ssh airflow-gpu-vm --command "
            sudo apt update &&
            sudo apt install -y docker.io &&
            cd ~/Processor_10K &&
            docker-compose down &&
            docker-compose build &&
            docker-compose up -d
          "
